openapi: 3.0.2
info:
  title: sample api
  description: for express-openapi sample
  version: 0.1.0
paths:
  /sample:
    get:
      summary: sample API endpoint
      description: get sample API
      operationId: getSample
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
components:
  schemas:
    Sample:
      type: object
      properties:
        name:
          type: string
      required:
        - name